project:
  type: website
  output-dir: docs
website:
  title: "Doc de Ener-Habitat"
  image: "images/enerhabitat.jpg"
  favicon: "images/logo_edited.png"
  page-navigation: true
  search: 
    show-item-context: true
    type: overlay
  page-footer: 
    left: |
      Derechos de autor . 2024 Documentación de Ener-Habitat
  navbar:
    background: light
    logo: images/enerhabitat.jpg
    logo-alt: "EnerHabitat logo."
    title: false
    collapse-below: xl
    left:
      - text: "Inicio"
        href: index.qmd
    tools:
      - icon: github
        href:  https://altamarmx.github.io/blog/2022/cursoPython/
        text: Learn Python
    
  sidebar: 
  - id: get-started
    text: "Empezar"
    style: floating
    collapse-level: 2
    align: left
    contents:
        - include/index.qmd
        - text: "Desarrollo de interfaz"
          href: include/interfaz.qmd
        - text: "Diccionarios"
          href: include/diccionaries.qmd
        - text: "Archivos creados"
          href: include/archivos.qmd
        - text: "Funciones generales"
          href: include/funciones.qmd
        - text: "Funciones del server"
          href: include/server.qmd
        - text: "Base de datos"
          href: include/bd.qmd

format:
  html:
    light: [cosmo, theme.scss]
    toc: true
    code-copy: true

freeze: true




